website/auth.py
"""
This module contains functions related to user authentication.
"""

from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import smtplib
from email.message import EmailMessage
import random
import string
from dotenv import load_dotenv
load_dotenv()  # This will load variables from .env into os.environ


# Create a blueprint for authentication routes
auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """
    Logs in a user if the submitted credentials are correct; otherwise, flashes an error.
    """
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    """
    Logs out the current user.
    """
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    """
    Registers a new user if the provided form data is valid.
    Otherwise, flashes an appropriate error message.
    """
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        
        # Check if the email or username already exists
        if User.query.filter_by(email=email).first():
            flash('Email already exists.', category='error')
        elif User.query.filter_by(username=username).first():
            flash('User name already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 2:
            flash('User name must be greater than 1 character.', category='error')
        elif len(username) > 20:
            flash('User name must be shorter than 21 characters.', category='error')
        elif password1 != password2:
            flash("Passwords don't match.", category='error')
        elif len(password1) < 4:
            flash('Password must be at least 4 characters.', category='error')
        else:
            # Create new user and add to database
            new_user = User(
                email=email,
                username=username,
                password=generate_password_hash(password1),
                fullname="Not specified",
                numModelsSaved="0",
                numTrainingsHistory="0"
            )
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user)


import os
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash
from . import db
from flask_login import current_user
import smtplib
from email.message import EmailMessage
import random
import string


@auth.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    """
    Resets the user's password if the provided email exists.
    Sends the new password via email; otherwise, flashes an error.
    """
    if request.method == 'POST':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()

        if user:
            # Generate a random 8-character password
            source = string.ascii_letters + string.digits
            generated_password = ''.join(random.choice(source) for _ in range(8))
            
            # Hash and update the user's password
            hashed_password = generate_password_hash(generated_password)
            user.password = hashed_password
            db.session.commit()
            
            # Prepare email content
            message = (
                "Hello, as you requested, a new password has been generated for your QKPDVSC account.\n\n"
                f"Your new password is: {generated_password}\n"
                "Feel free to change your password from your profile if you feel it is convenient.\n\n"
                "Best regards, the administrator."
            )
            em = EmailMessage()
            em['From'] = os.environ.get('EMAIL_ADDRESS')
            em['To'] = email
            em['Subject'] = "New password for your QKPDVSC account"
            em.set_content(message)

            # Send the email using SMTP with credentials from the environment
            smtp_server = os.environ.get('SMTP_SERVER', 'smtp.gmail.com')
            smtp_port = int(os.environ.get('SMTP_PORT', 587))
            server = smtplib.SMTP(smtp_server, smtp_port)
            server.starttls()
            server.login(os.environ.get('EMAIL_ADDRESS'), os.environ.get('EMAIL_PASSWORD'))
            server.sendmail(os.environ.get('EMAIL_ADDRESS'), email, em.as_string())
            server.quit()
            
            flash("An email has been sent to this address with the new password.", category='success')
        else:
            flash("There is no user registered with this email address. Try again.", category='error')

    return render_template("forgot_password.html", user=current_user)

website/templates/admin.html
{% extends "baseViews.html" %} {% block title %}Admin Settings{% endblock %} <!-- Extiende el base-html. Será exactamente igual excepto el título-->
{% block content %}
  <p>&emsp;</p>
  <h1 align="left"><b>ADMIN SETTINGS</b></h1>
  <hr>
  <p>&emsp;</p>

  <h5 align="center"><b>LIST OF USERS</b></h5>
  <p>&ensp;</p>

  <form method="POST">
    <div align="center">
      <select id="selectBoxAdminSettings" name="selectBoxAdminSettings" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
      {% if existsUsers == True %}
        {% for username in listaUsernames %}
          {% if username != 'admin' %}
            {% if username == userChosen.username %}
              <option selected value="{{ username }}">{{ username }}</option>
            {% else %}
              <option value="{{ username }}">{{ username }}</option>
            {% endif %}
          {% endif %}
        {% endfor %}
      {% endif %}
      </select>
    </div>

    <p>&ensp;</p>
    {% if existsUsers == True %}
    <div class="row">
      <div class="col-sm-3">
        <button id="adminSettingsButton" type="submit" name="adminSettingsButton" value="createUserButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
          Create new user
        </button>
      </div>
      <div class="col-sm-3">
        <button id="adminSettingsButton" type="submit" name="adminSettingsButton" value="viewUserButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
          View user info
        </button>
      </div>
      <div class="col-sm-3">
        <button id="adminSettingsButton" type="submit" name="adminSettingsButton" value="modifyUserButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
          Modify user
        </button>
      </div>
      <div class="col-sm-3">
        <button id="adminSettingsButton" type="submit" name="adminSettingsButton" value="deleteUserButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
          Delete user
        </button>
      </div>
    </div>
      
    {% else %}
      <div id="NoUsersWarning" class="alert alert-danger alter-dismissable fade show" role="alert" align="center">
        There are no more users than the administrator.
      </div>
    {% endif %}
    
    <hr>
          
  <p>&ensp;</p>

  {% if flagBotonCreateNewUser == True %}

  <div class="card mb-3">
    <div class="card-body">
        <h4 align="center"><b>CREATE NEW USER</b></h4>
        <p>&ensp;</p>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Full Name</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="text" class="form-control" value="" name="fullnameCreate" id="fullnameCreate">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Email</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="email" class="form-control" value="" name="emailCreate" id="emailCreate">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">User name</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="text" class="form-control" value="" name="usernameCreate" id="usernameCreate">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Password</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="password" class="form-control" name="password1Create" id="password1Create">
          </div>
        </div>
        <p>&ensp;</p>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Repeat password</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="password" class="form-control" name="password2Create" id="password2Create">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-12">
            
              <button id="createUserAdminButton" type="submit" name="adminSettingsButton" value="createUserAdminButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
                Create user
              </button>
            
          </div>
        </div>
    </div>
  </div>

  {% elif flagBotonViewUserInfo == True %}

  <div class="card mb-3">
    <div class="card-body">
      <h4 align="center"><b>VIEW USER INFO</b></h4>
      <p>&ensp;</p>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Full Name</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ userChosen.fullname }}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Email</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ userChosen.email}}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">User name</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ userChosen.username}}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">User ID</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ userChosen.id}}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Number of models saved</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ userChosen.numModelsSaved}}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 class="mb-0">Number of pdf reports saved</h6>
        </div>
        <div class="col-sm-9 text-secondary">
          {{ userChosen.numTrainingsHistory}}
        </div>
      </div>
      <hr>
    </div>
  </div>

  {% elif flagBotonModifyUser == True %}

    <div class="card mb-3">
      <div class="card-body">
        <h4 align="center"><b>MODIFY USER</b></h4>
        <p>&ensp;</p>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Full Name</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="text" class="form-control" value="{{ userChosen.fullname }}" name="fullname" id="fullname">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Email</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="email" class="form-control" value="{{ userChosen.email }}" name="email" id="email">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">User name</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="text" class="form-control" value="{{ userChosen.username }}" name="username" id="username">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Password</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="password" class="form-control" name="password1" id="password1">
          </div>
        </div>
        <p>&ensp;</p>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Repeat password</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <input type="password" class="form-control" name="password2" id="password2">
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-12">
            
              <button id="modifyUserAdminButton" type="submit" name="adminSettingsButton" value="modifyUserAdminButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
                Save changes
              </button>
            
          </div>
        </div>
      </div>
    </div>

  {% elif flagBotonDeleteUser == True %}

  <div class="card mb-3">
    <div class="card-body">
      <h4 align="center"><b>DELETE USER</b></h4>
      <p>&ensp;</p>
      <hr>
      <h5 class="mb-0" align="center">Are you sure you want to delete this user?</h5>
      <p>&ensp;</p>
      <h6 class="mb-0" align="center">{{ userChosen.username }}</h6>
      <p>&ensp;</p>
      <div class="row">
        <div class="col-sm-3">
        </div>
        <div class="col-sm-3">
          <button id="cancelDeleteAdminButton" type="submit" name="adminSettingsButton" value="cancelDeleteAdminButton" class="btn btn-secondary btn-md" style="color: #ffffff; width: 100%;" align="right">
            Cancel
          </button>
        </div>
        
        <div class="col-sm-3 text-secondary">
          <button id="deleteUserAdminButton" type="submit" name="adminSettingsButton" value="deleteUserAdminButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
            Delete
          </button>
        </div>
      </div>
      
    </div>
  </div>
  {% endif %}
  </form>

  <p>&ensp;</p>
  <p>&emsp;</p>
  <p>&emsp;</p>

{% endblock %}

website/templates/baseAuth.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> <!-- que el tamaño se ajuste al tamaño de la pantalla -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    /> <!-- Estos links permiten usar estilos bootstrap sin descargarlos de verdad -->

    <title>{% block title %}Home{% endblock %}</title> <!-- Los blocks podrán ser cambiados por otra de las templates, pues sobreescribirán esta template -->
  </head>
  <body>

    {% with messages = get_flashed_messages(with_categories=true) %} <!-- get_flashed_messages es una función ya existente en Flask -->
      {% if messages %}
        {% for category, message in messages %} 
          {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% else %}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div> <!-- El container añade margenes -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script> <!-- Así es como se carga una imagen o archivo del folder static. Los 2 paréntesis indican que dentro habrá codigo python-->
  </body>
</html>


website/templates/editProfile.html
{% extends "baseViews.html" %} {% block title %}Edit profile{% endblock %} <!-- Extiende el base-html. Será exactamente igual excepto el título-->
{% block content %}
  <p>&emsp;</p>
  <h1 align="left"><b>PROFILE</b></h1>
  <hr>
  <p>&emsp;</p>
  <div class="container">
    <div class="main-body">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card" style=" height: 36em;">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{user.username}}</h4>
                      {% if user.username == 'admin' %}
                        <p class="text-secondary mb-1">Administrator</p>
                      {% else %}
                      <p class="text-secondary mb-1">Ordinary User</p>
                      {% endif %}
                      <p class="text-secondary mb-1">User ID: {{ user.id }}</p>
                      <p>&ensp;</p>
                    </div>
                    <div class="card text-center" style="border-radius: 50%; height: 4em; width: 7em;">
                      <div class="card-body" style="background-color: #8ad383; border-radius: 10%;">
                        <h6>Logged</h6>
                      </div>
                    </div>
                    <p>&emsp;</p>
                    <p>&emsp;</p>
                    <p>&emsp;</p>
                    <form method="post">
                      <button id="editProfileButtons" type="submit" name="editProfileButtons" value="buttonDeleteAccount" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
                        Delete account
                      </button>
                    </form>
                  </div>
                  
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <form method="POST">
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Full Name</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <input type="text" class="form-control" value="{{ user.fullname }}" name="fullname" id="fullname">
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Email</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <input type="email" class="form-control" value="{{ user.email }}" name="email" id="email">
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">User name</h6>
                      </div>
                      {% if user.username == 'admin' %}
                        <div class="col-sm-9 text-secondary">
                          <p>admin</p>
                          </p><b style="color: #e06666;"> It is not possible to change admin user name.</b></p>
                        </div>
                      {% else %}
                        <div class="col-sm-9 text-secondary">
                          <input type="text" class="form-control" value="{{ user.username }}" name="username" id="username">
                        </div>
                      {% endif %}
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Password</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <input type="password" class="form-control" name="password1" id="password1">
                      </div>
                    </div>
                    <p>&ensp;</p>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Repeat password</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <input type="password" class="form-control" name="password2" id="password2">
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-12">
                        
                          <button id="editProfileButtons" type="submit" name="editProfileButtons" value="saveProfileButton" class="btn btn-primary btn-md" style="color: #ffffff; width: 100%;" align="right">
                            Save changes
                          </button>
                        
                      </div>
                    </div>
                  </form>
                </div>
              </div>

              <div class="row gutters-sm text-center">
                <div class="col-sm-6 mb-3">
                  <div class="card">
                    <div class="card-body">
                      <h6 style="color: #FA7C0D; padding-bottom: 0.5em;"><b>Number of models saved</b></h6>
                      <h3>{{ user.numModelsSaved }}</h3>
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card">
                    <div class="card-body">
                      <h6 style="color: #FA7C0D; padding-bottom: 0.5em;"><b>Number of pdf reports saved</b></h6>
                      <h3>{{ user.numTrainingsHistory }}</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
    </div>

    <p>&emsp;</p>
    <p>&emsp;</p>

{% endblock %}



















website/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> <!-- que el tamaño se ajuste al tamaño de la pantalla -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/style.css')}}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    /> <!-- Estos links permiten usar estilos bootstrap sin descargarlos de verdad -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/baseViews.css') }}"
    />

    <!-- <title>{% block title %}Home{% endblock %}</title>  Los blocks podrán ser cambiados por otra de las templates, pues sobreescribirán esta template -->
  </head>
  <body>
    

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6e6;"> <!-- Esto son clases de Bootstrap -->
      <button
        id="navbarCollapsedButton"
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      > <!-- Permite expandir el navbar si no entra, por ejemplo en pantalla de movil -->
        <span id="navbarCollapsedIcon" class="navbar-toggler-icon"></span> <!-- Es el icono de la navbar -->
      </button>
      <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav">
            <a id="QKPDVSC" class="navbar-brand" href="/login">QKPDVSC</a>
          </ul>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}

    <section class="vh-100">
      <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center col-md-9 col-lg-6 col-xl-5">
            <img src="{{ url_for('static', filename='images/logoAPP2.PNG')}}"
              class="img-fluid" alt="Logo image" style="width: 55%; height: 55%;" >
          </div>
          <div class="d-flex flex-column min-vh-100 justify-content-center align-items-center col-md-8 col-lg-6 col-xl-4 offset-xl-1">
              <form method="POST">
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example3">Email address</label>
                  <input type="email" id="email" name="email" class="form-control form-control-lg"
                    placeholder="email address" />
                </div>
      
                
                <div class="form-outline mb-3">
                  <label class="form-label" for="form3Example4">Password</label>
                  <input type="password" id="password" name="password" class="form-control form-control-lg"
                    placeholder="password" />
                </div>
      
                <div class="d-flex flex-column justify-content-between align-items-center">
                  <a href="{{ url_for('auth.forgot_password') }}" class="link-danger">Forgot password?</a>
                </div>
      
                <div class="text-center text-lg-start mt-4 pt-2">
                  <button type="submit" name="loginButton" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{{ url_for('auth.sign_up') }}" class="link-danger">Register</a></p>
                </div>
      
              </form>
          </div>
        </div>
      </div>
    </section>

    


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script> <!-- Así es como se carga una imagen o archivo del folder static. Los 2 paréntesis indican que dentro habrá codigo python-->
  </body>
</html>